CREATE TABLE documento_carga (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_documento VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'DISPONIVEL',
    peso DECIMAL(10, 2),
    valor DECIMAL(15, 2),
    volume DECIMAL(10, 2),
    regiao VARCHAR(20),
    versao INT DEFAULT 1
);

CREATE INDEX idx_doc_status ON documento_carga (status);
CREATE INDEX idx_doc_filtro_completo ON documento_carga (status, regiao, valor, peso, volume);

CREATE TABLE planejamento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    status VARCHAR(20) DEFAULT 'DRAFT',
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE planejamento_item (
    planejamento_id INTEGER REFERENCES planejamento(id),
    documento_id INTEGER REFERENCES documento_carga(id),
    PRIMARY KEY (planejamento_id, documento_id),
    CONSTRAINT unique_documento_reserva UNIQUE (documento_id) 
);